language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

env:
  global:
      secure: "jwmoa4BufY6bz3qR6UP5iQWVAnXpp7FrW75ehqheXJdQx3CWBJ8aX8gV9qXkPuPyRr3ubV8gyLx4iQ1/PSJbhPxA2BGYDpJcwOVN4e8G4kOcFYTaGW3CQsP/V8uwFX0jzsyqVExsjTdvsu88zxwaQFLyEV9T7gcHB9b+ECXaOB0="

before_script:
  - composer self-update
  - composer install

# Report test coverate to code climate
after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
